# Generated by Django 5.2 on 2025-04-26 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_alter_player_guild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="guild",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.guild"
            ),
        ),
    ]
